import './globals.css';
import type { Metadata } from 'next';
import { AppProvider } from './Provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="font-dm pb-12">
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
